# Generated by Django 6.0.3 on 2026-05-12 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150)),
                ('nome_categoria', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'api_categoria',
            },
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id_dono', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('senha', models.CharField(max_length=8)),
                ('status_dono', models.CharField(max_length=1)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cor_brinco', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao_marca', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'dono',
            },
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id_leilao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_evento', models.CharField(max_length=150)),
                ('dt_leilao', models.DateField()),
                ('custo_fixo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'api_leilao',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('sexo', models.CharField(max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dt_nasc', models.DateField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('id_dono', models.ForeignKey(db_column='id_dono', on_delete=django.db.models.deletion.CASCADE, to='api.dono')),
            ],
            options={
                'db_table': 'api_animal',
            },
        ),
    ]
